### ISSUE TITLE
ValueError: non-integer stop for randrange()

### ISSUE THREAD

**Issue by BBArikL** [ByteBaker/randomtimestamp#1]
When calling randomtimestamp() with datetime having seconds and the other one just plain date, the method goes crazy and fail. The fix is to determine the end datetime to 0 for hours, minutes, seconds and microseconds.
first_date = 1989-04-16 00:00:00
end = 2021-10-04 22:17:16.962387

```
Traceback (most recent call last):
.........
  File "C:\Users\<>\<>\<>\<>.py", line 109, in get_random_link
    random_date = randomtimestamp.randomtimestamp(start=first_date, end=datetime.today())
  File "C:\Users\<>\AppData\Local\Programs\Python\Python39\lib\site-packages\randomtimestamp\functions.py", line 49, in randomtimestamp
    stamp = get_datetime(start_dtime, end_dtime)
  File "C:\Users\<>\AppData\Local\Programs\Python\Python39\lib\site-packages\randomtimestamp\core.py", line 214, in get_datetime
    random_gap_seconds = randint(0, gap_seconds)
  File "C:\Users\<>\AppData\Local\Programs\Python\Python39\lib\random.py", line 338, in randint
    return self.randrange(a, b+1)
  File "C:\Users\<>\AppData\Local\Programs\Python\Python39\lib\random.py", line 311, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()
```
If it is not something you plan to fix, this could be at least mentionned so people don't enter wrong datetime objects. Have a good day!

**Comment by ByteBaker** [comment]
Thank you for pointing out and raising the issue. The patch has been committed and the issue closed.
